// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars_App.Data;

#nullable disable

namespace StarWars_App.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230527151628_add_film_character")]
    partial class add_film_character
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("StarWars_App.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT");

                    b.Property<string>("EyeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HairColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOrign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Planet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Race")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = "896",
                            Destination = "Описание",
                            EyeColor = "Зеленый",
                            HairColor = "Белый",
                            Height = 0.66f,
                            Name = "Йода",
                            NameOrign = "Yoda",
                            Planet = "Дагоба",
                            Race = "Раса Йоды",
                            Sex = "Мужчина"
                        });
                });

            modelBuilder.Entity("StarWars_App.Models.CharacterFilm", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilmId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "FilmId");

                    b.HasIndex("FilmId");

                    b.ToTable("CharacterFilms");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            FilmId = 2
                        },
                        new
                        {
                            CharacterId = 1,
                            FilmId = 3
                        },
                        new
                        {
                            CharacterId = 1,
                            FilmId = 4
                        },
                        new
                        {
                            CharacterId = 1,
                            FilmId = 6
                        },
                        new
                        {
                            CharacterId = 1,
                            FilmId = 7
                        },
                        new
                        {
                            CharacterId = 1,
                            FilmId = 8
                        },
                        new
                        {
                            CharacterId = 1,
                            FilmId = 9
                        });
                });

            modelBuilder.Entity("StarWars_App.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Эпизод IV — Новая надежда"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Эпизод V — Империя наносит ответный удар"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Эпизод VI — Возвращение джедая"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Эпизод I — Скрытая угроза"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Эпизод II — Атака клонов"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Эпизод III — Месть ситхов"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Эпизод VII — Пробуждение силы"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Эпизод VIII — Последние джедаи"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Эпизод IX — Скайуокер. Восход"
                        });
                });

            modelBuilder.Entity("StarWars_App.Models.CharacterFilm", b =>
                {
                    b.HasOne("StarWars_App.Models.Character", "Character")
                        .WithMany("Films")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StarWars_App.Models.Film", "Film")
                        .WithMany("Characters")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("StarWars_App.Models.Character", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("StarWars_App.Models.Film", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
